<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="0">

  <testsuite name="auth-flow"
    errors="1" failures="0" hostname="" id="" package="auth-flow" skipped="3"
    tests="0" time="0.000" timestamp="">
  

  
    <system-err>
        Error: An error occurred while retrieving a new session
       at endReadableNT (_stream_readable.js:1220:12)
       at processTicksAndRejections (internal/process/task_queues.js:84:21)
    </system-err>
  

    
    <error message="An error occurred while retrieving a new session"><![CDATA[
      Error: An error occurred while retrieving a new session
    at JsonWireProtocol.handleSessionCreateError (C:\Users\takudzwa shumbamhini\AppData\Roaming\npm\node_modules\nightwatch\lib\transport\transport.js:103:15)
    at HttpRequest.&lt;anonymous&gt; (C:\Users\takudzwa shumbamhini\AppData\Roaming\npm\node_modules\nightwatch\lib\transport\transport.js:159:32)
    at HttpRequest.emit (events.js:315:20)
    at HttpResponse.&lt;anonymous&gt; (C:\Users\takudzwa shumbamhini\AppData\Roaming\npm\node_modules\nightwatch\lib\http\request.js:142:19)
    at HttpResponse.emit (events.js:315:20)
    at IncomingMessage.&lt;anonymous&gt; (C:\Users\takudzwa shumbamhini\AppData\Roaming\npm\node_modules\nightwatch\lib\http\response.js:60:14)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
      ]]></error>  

  
    
    <testcase
      name="get to login page" classname="auth-flow">
      <skipped />
    </testcase>
    
    <testcase
      name="logging out" classname="auth-flow">
      <skipped />
    </testcase>
    
    <testcase
      name="close" classname="auth-flow">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
